# Generated by Django 2.2.4 on 2019-08-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190820_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategorybrand',
            options={'verbose_name': '宣传品牌', 'verbose_name_plural': '宣传品牌'},
        ),
    ]
